apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  annotations:
    docs.mlopscourse.dev/link: "https://github.com/Oleksandr-Ho/goit-argo"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Oleksandr-Ho/goit-argo.git
    path: charts/mlflow
    targetRevision: main
    helm:
      releaseName: mlflow
      values: |
        service:
          type: ClusterIP
          port: 5000
        image:
          repository: mlflow/mlflow
          tag: 2.9.2
        minio:
          enabled: false
        postgresql:
          enabled: false
        tracking:
          auth:
            enabled: false
          persistence:
            enabled: false
        run:
          enabled: false
        mlflow:
          defaultArtifactRoot: /mlruns
          extraEnvVars:
            - name: MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT
              value: /mlruns
            - name: MLFLOW_SERVER_PORT
              value: "5000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
