apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  annotations:
    docs.mlopscourse.dev/link: "https://charts.bitnami.com/bitnami"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mlflow
    targetRevision: 2.4.6
    helm:
      releaseName: mlflow
      values: |
        service:
          type: ClusterIP
          port: 5000
        mlflow:
          defaultArtifactRoot: /bitnami/mlflow
          extraEnvVars:
            - name: MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT
              value: /bitnami/mlflow
            - name: MLFLOW_SERVER_PORT
              value: "5000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
        backendStore:
          database:
            enabled: true
            postgresql:
              primary:
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 250m
                    memory: 512Mi
        artifactStore:
          enabled: true
          minio:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 250m
                memory: 512Mi
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
